name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase
        working-directory: ./webapp
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}